AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda GraphQL function + DynamoDB.
Parameters:
    EnvName:
        Type: String
        Description: Choose 'test' or 'prod'. This generates an alias, stage and sets NODE_ENV.
        AllowedValues:
            - test
            - prod
        Default: test
Outputs:
    LambdaFunctionName:
        Value: !Ref GraqhQLLambdaFunction
    LambdaFunctionARN:
        Description: Lambda function ARN.
        Value:
            'Fn::GetAtt':
                - GraqhQLLambdaFunction
                - Arn
        Export:
            Name: !Sub LambdaARN-${EnvName}
    ApiURL:
        Description: 'API endpoint URL for the environment'
        Value: !Sub https://${GraqhQLApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${EnvName}/graphql
Resources:
    GraqhQLLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            Description: An AWS Lambda GraphQL function.
            FunctionName: !Sub graphql-lambda-function-${EnvName}
            AutoPublishAlias: !Ref EnvName
            Handler: src/lambda.handler
            CodeUri: .
            Runtime: nodejs10.x
            MemorySize: 256
            Timeout: 10
            Tracing: Active
            Events:
                AnyRequest:
                    Type: Api
                    Properties:
                        Path: /graphql
                        Method: ANY
                        RestApiId: !Ref GraqhQLApiGateway
            Environment:
                Variables:
                    NODE_ENV: !Ref EnvName
    GraqhQLApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref EnvName
            TracingEnabled: True
