AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda GraphQL function + DynamoDB.
Parameters:
    EnvName:
        Type: String
        Description: Choose 'test' or 'prod'. This generates an alias, stage and sets NODE_ENV.
        AllowedValues:
            - test
            - prod
        Default: test
Mappings:
    TablePrefixMap:
        test:
            Prefix: 'test_'
        prod:
            Prefix: ''
Resources:
    GraphQLLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            Description: An AWS Lambda GraphQL function.
            FunctionName: !Sub graphql-lambda-function-${EnvName}
            AutoPublishAlias: !Ref EnvName
            Handler: src/lambda.handler
            CodeUri: .
            Runtime: nodejs10.x
            MemorySize: 128
            Timeout: 10
            Tracing: Active
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref MoviesTable
            Events:
                AnyRequest:
                    Type: Api
                    Properties:
                        Path: /graphql
                        Method: ANY
                        RestApiId: !Ref GraphQLApiGateway
            Environment:
                Variables:
                    NODE_ENV: !Ref EnvName
    GraphQLApiGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref EnvName
            TracingEnabled: True
    MoviesTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: !Join
                - ''
                - - !FindInMap [TablePrefixMap, !Ref EnvName, Prefix]
                  - 'movies'
            BillingMode: PAY_PER_REQUEST
            KeySchema:
                - AttributeName: year
                  KeyType: HASH
                - AttributeName: title
                  KeyType: RANGE
            AttributeDefinitions:
                - AttributeName: year
                  AttributeType: N
                - AttributeName: title
                  AttributeType: S
Outputs:
    LambdaFunctionName:
        Value: !Ref GraphQLLambdaFunction
    LambdaFunctionARN:
        Description: Lambda function ARN.
        Value:
            'Fn::GetAtt':
                - GraphQLLambdaFunction
                - Arn
    ApiURL:
        Description: 'API endpoint URL for the environment'
        Value: !Sub https://${GraphQLApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${EnvName}/graphql
    MoviesTableARN:
        Description: DynamoDB Movies table ARN.
        Value:
            'Fn::GetAtt':
                - MoviesTable
                - Arn
