name: CD to test

on:
    push:
        branches: master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install
              run: |
                  npm install
            - name: npm audit
              run: |
                  npm run audit
            - name: lint
              run: |
                  npm run lint
            - name: compile
              run: |
                  npm run compile
            - name: npm run and test
              run: |
                  npm run run-then-test
              env:
                  NODE_ENV: ci
                  PORT: 3000
                  CONSOLE_LOGGING_DISABLED: true
                  AWS_REGION: us-east-1
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: build, package and deploy
              run: |
                  npm run build:webpack
                  npm run package:cf
                  npm run deploy:cf
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: us-east-1
