name: CD to test

on:
    push:
        branches: master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: CI
              uses: ./.github/actions/ci
            - name: build, package and deploy
              run: |
                  npm run build:webpack
                  npm run package:cf
                  npm run deploy:cf
              env:
                  AWS_REGION: us-east-1
                  AWS_DEFAULT_REGION: us-east-1
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
