name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, lint, compile, run and test
              run: |
                  npm install
                  npm run lint
                  npm run compile
                  npm run run-then-test
              env:
                  NODE_ENV: dev
                  PORT: 3000
                  AWS_REGION: us-east-1
              secrets: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
